export const cidades = [
  "São Paulo",
  "Rio de Janeiro",
  "Brasília",
  "Salvador",
  "Belo Horizonte",
  "Fortaleza",
  "Curitiba",
  "Manaus",
  "Recife",
  "Goiânia",
  "Belém",
  "Porto Alegre",
  "Guarulhos",
  "Campinas",
  "São Luís",
  "São Gonçalo",
  "Maceió",
  "Duque de Caxias",
  "Campo Grande",
  "Natal",
  "Teresina",
  "São Bernardo do Campo",
  "João Pessoa",
  "Nova Iguaçu",
  "São José dos Campos",
  "Santo André",
  "Ribeirão Preto",
  "Jaboatão dos Guararapes",
  "Uberlândia",
  "Osasco",
  "Sorocaba",
  "Contagem",
  "Aracaju",
  "Feira de Santana",
  "Cuiabá",
  "Joinville",
  "Aparecida de Goiânia",
  "Londrina",
  "Juiz de Fora",
  "Porto Velho",
  "Ananindeua",
  "Serra",
  "Caxias do Sul",
  "Macapá",
  "Niterói",
  "Florianópolis",
  "Belford Roxo",
  "Campos dos Goytacazes",
  "Vila Velha",
  "Mauá",
  "São João de Meriti",
  "São José do Rio Preto",
  "Mogi das Cruzes",
  "Betim",
  "Boa Vista",
  "Maringá",
  "Santos",
  "Diadema",
  "Jundiaí",
  "Rio Branco",
  "Montes Claros",
  "Campina Grande",
  "Piracicaba",
  "Carapicuíba",
  "Anápolis",
  "Olinda",
  "Cariacica",
  "Bauru",
  "Itaquaquecetuba",
  "São Vicente",
  "Vitória",
  "Caruaru",
  "Caucaia",
  "Blumenau",
  "Petrolina",
  "Ponta Grossa",
  "Franca",
  "Canoas",
  "Pelotas",
  "Vitória da Conquista",
  "Ribeirão das Neves",
  "Uberaba",
  "Paulista",
  "Praia Grande",
  "Cascavel",
  "São José dos Pinhais",
  "Guarujá",
  "Taubaté",
  "Palmas",
  "Limeira",
  "Camaçari",
  "Santarém",
  "Petrópolis",
  "Mossoró",
  "Suzano",
  "Taboão da Serra",
  "Várzea Grande",
  "Sumaré",
  "Marabá",
  "Gravataí",
  "Santa Maria",
  "Governador Valadares",
  "Barueri",
  "Embu das Artes",
  "Juazeiro do Norte",
  "Volta Redonda",
  "Parnamirim",
  "Ipatinga",
  "Macaé",
  "Indaiatuba",
  "Imperatriz",
  "Foz do Iguaçu",
  "Cotia",
  "Viamão",
  "São Carlos",
  "São José",
  "Colombo",
  "Magé",
  "Novo Hamburgo",
  "Rio Verde",
  "Itaboraí",
  "Americana",
  "Itapevi",
  "Sete Lagoas",
  "Divinópolis",
  "Marília",
  "Araraquara",
  "São Leopoldo",
  "Rondonópolis",
  "Hortolândia",
  "Jacareí",
  "Arapiraca",
  "Cabo Frio",
  "Presidente Prudente",
  "Maracanaú",
  "Dourados",
  "Chapecó",
  "Itajaí",
  "Águas Lindas de Goiás",
  "Santa Luzia",
  "Juazeiro",
  "Criciúma",
  "Parauapebas",
  "Luziânia",
  "Itabuna",
  "Rio Grande",
  "Sobral",
  "Alvorada",
  "Cachoeiro de Itapemirim",
  "Cabo de Santo Agostinho",
  "Angra dos Reis",
  "Rio Claro",
  "Passo Fundo",
  "Castanhal",
  "Lauro de Freitas",
  "Araçatuba",
  "Ferraz de Vasconcelos",
  "Santa Bárbara d'Oeste",
  "Nova Friburgo",
  "Nossa Senhora do Socorro",
  "Araguaína",
  "Teresópolis",
  "Barra Mansa",
  "Jaraguá do Sul",
  "Ibirité",
  "Guarapuava",
  "São José de Ribamar",
  "Linhares",
  "Itapecerica da Serra",
  "Francisco Morato",
  "Palhoça",
  "Itu",
  "Mesquita",
  "Valparaíso de Goiás",
  "Bragança Paulista",
  "Pindamonhangaba",
  "Timon",
  "Poços de Caldas",
  "Maricá",
  "Itapetininga",
  "Caxias",
  "Teixeira de Freitas",
  "Nilópolis",
  "São Caetano do Sul",
  "Abaetetuba",
  "Camaragibe",
  "Rio das Ostras",
  "Franco da Rocha",
  "Barreiras",
  "Ilhéus",
  "Paranaguá",
  "Lages",
  "Jequié",
  "Patos de Minas",
  "Pouso Alegre",
  "Mogi Guaçu",
  "Parnaíba",
  "Jaú",
  "Alagoinhas",
  "Porto Seguro",
  "Queimados",
  "Botucatu",
  "Balneário Camboriú",
  "Sinop",
  "Araucária",
  "Atibaia",
  "Santana de Parnaíba",
  "Toledo",
  "Sapucaia do Sul",
  "Garanhuns",
  "Teófilo Otoni",
  "Cametá",
  "Brusque",
  "Vitória de Santo Antão",
  "Barbacena",
  "Santa Rita",
  "Sabará",
  "Varginha",
  "Apucarana",
  "Simões Filho",
  "Araras",
  "Itaguaí",
  "Araruama",
  "Marituba",
  "São Félix do Xingu",
  "Campo Largo",
  "Pinhais",
  "São Mateus",
  "Crato",
  "Resende",
  "Valinhos",
  "Cubatão",
  "Santa Cruz do Sul",
  "Cachoeirinha",
  "Trindade",
  "Vespasiano",
  "Itapipoca",
  "Maranguape",
  "Ji-Paraná",
  "Conselheiro Lafaiete",
  "Bragança",
  "Barcarena",
  "Guarapari",
  "Sertãozinho",
];
